version: "3.8"
services:
  backend:
    image: "dmitriikonnovnn/exam-microservice-fs:1.4.2022.21.47.24"
    ports:
      - "80:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev