version: "3.8"
services:
  backend:
    image: "dmitriikonnovnn/exam-microservice-fs:4.4.2022.16.48.26"
    ports:
      - "80:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev


