version: "3.8"
services:
  backend:
    image: "dmitriikonnovnn/exam-microservice-fs:7.6.2022.17.8.10"
    ports:
      - "80:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev


