version: "3.8"
services:
  backend:
    image: "dmitriikonnovnn/exam-microservice-fs:29.3.2022.15.24.20"
    ports:
      - "80:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev