version: "3.8"
services:
  backend:
    image: "dmitriikonnovnn/exam-microservice-fs:31.3.2022.13.20.47"
    ports:
      - "80:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev