version: "3.8"
services:
  backend:
    image: "dmitriikonnovnn/exam-microservice-fs:24.3.2023.11.34.4"
    ports:
      - "80:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL="jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}"
      - SPRING_DATASOURCE_USERNAME=${RDS_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${RDS_PASSWORD}
      - JAVA_TOOL_OPTIONS="-Xms150M -Xmx150M"



