version: "3.8"
services:
  backend:
    image: "dmitriikonnovnn/exam-microservice-fs:24.5.2022.11.4.25"
    ports:
      - "80:8080"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev


