spring:
  profiles:
    active: local,dev,local-db

---

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://aaahqt3ykxldk9.ccca0rwlbn76.eu-central-1.rds.amazonaws.com:5432/exams_microservice
    username: dmitrikonnovnn
    password: 2ii28ei6o49o

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  config:
    activate:
      on-profile: dev
  flyway:
    baseline-on-migrate: true
    enabled: true

---

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/exams_microservice
    username: postgres
    password: P@s$w0rD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  config:
    activate:
      on-profile: local
  flyway:
    baseline-on-migrate: false
    enabled: true
---

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exam_microservice
    driver-class-name: org.postgresql.Driver
    password: 'P@ssw0rd'
    pool-size: 30
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: false
  config:
    activate:
      on-profile: local-db
  flyway:
    baseline-on-migrate: true
    enabled: true





