spring:
  profiles:
    active: local,dev

---

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://aadfm7ls4thv2l.ctdfxixgdw3f.eu-west-1.rds.amazonaws.com:5432/exams_microservice
    username: dmitrikonnovnn
    password: 2ii28ei6o49o

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  config:
    activate:
      on-profile: dev

---

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/exams_microservice
    username: postgres
    password: P@s$w0rD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  config:
    activate:
      on-profile: local

