spring:
  profiles:
    active: local,dev,staging

---

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://cname.prefix.aws-region-az.rds.amazonaws.com:5432/exams_microservice
    driver-class-name: org.postgresql.Driver
    username: username
    password: password
  application:
    name: @name@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  config:
    activate:
      on-profile: dev
  flyway:
    baseline-on-migrate: true
    enabled: false

info:
  app:
    name: @name@
    description: none
    version: @version@
management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-components: always
      show-details: always
  metrics:
    enable:
      http:
        client:
          requests: true
        server:
          requests: true
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

---


server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://cname.prefix.aws-region-az.rds.amazonaws.com:5432/exams_microservice
    driver-class-name: org.postgresql.Driver
    username: username
    password: password
  application:
    name: @name@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  config:
    activate:
      on-profile: staging
  flyway:
    baseline-on-migrate: true
    enabled: false

info:
  app:
    name: @name@
    description: none
    version: @version@
management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-components: always
      show-details: always
  metrics:
    enable:
      http:
        client:
          requests: true
        server:
          requests: true
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

---

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/exams_microservice
    driver-class-name: org.postgresql.Driver
    username: dmitri
    password: P@ssw0rD
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  config:
    activate:
      on-profile: local
  flyway:
    baseline-on-migrate: false
    enabled: false
  devtools:
    add-properties: true
info:
  app:
    name: @name@
    description: none
    version: @version@
management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-components: always
      show-details: always
  metrics:
    enable:
      http:
        client:
          requests: true
        server:
          requests: true
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true




