global:
  scrape_interval: 15s
  evaluation_interval: 15s # evaluate rules every 15 seconds
rule_files:
# - "some.rules" we can declare a rule file where we describe a certain condition for getting alerts.
# see more: https://prometheus:io/docs/prometheus/latest/configuration/alerting_rules/
# - "onemore.rules"
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'spring-actuator'
    metrics_path: 'actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9001']
  # consider using PORT 9001 because our actuator/prometheus is exposed there!