name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  POSTGRESQL_VERSION: postgres:12.8
  POSTGRESQL_DB: exams_microservice
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: P@s$w0rD
  JAVA_VERSION: 11

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        db: [postgres:12.8]
    services:
      postgres:
        image: ${{matrix.db}}
        env:
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        ports:
          - 5433:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Maven Clean Package
        run: |
          ./mvnw --no-transfer-progress clean package -P build-frontend