name: CI

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

env:
  POSTGRESQL_VERSION: 12.8
  POSTGRESQL_DB: exams_microservice
  POSTGRESQL_USER: dmitri
  POSTGRESQL_PASSWORD: P@ssw0rD
  JAVA_VERSION: 17
  JAVA_DISTRO: oracle
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.8
        env:
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        ports:
          - 5433:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{env.JAVA_DISTRO}}
          cache: 'maven'
          check-latest: false
      - name: Maven Clean Package & Build Frontend
        run: |
          ./mvnw --no-transfer-progress clean package -P build-frontend