name: STAGING

on:
  push:
    branches: [ staging ]

  workflow_dispatch:

env:

  POSTGRESQL_VERSION: 12.8
  POSTGRESQL_DB: exams_microservice
  POSTGRESQL_USER: dmitri
  POSTGRESQL_PASSWORD: P@ssw0rD
  CI: false

  JAVA_VERSION: 17
  JAVA_DISTRO: oracle

  DOCKER_HUB_USERNAME: dmitriikonnovnn

  AWS_REGION: us-east-1
  EB_ENVIRONMENT_NAME: staging
  EB_APPLICATION_NAME: exams-management
  EB_DEPLOYMENT_PACKAGE: elasticbeanstalk/staging/docker-compose.yaml

jobs:
  deploy-into-staging:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.8
        env:
          POSTGRES_DB: ${{ env.POSTGRESQL_DB }}
          POSTGRES_USER: ${{ env.POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRESQL_PASSWORD }}
        ports:
          - 5433:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: 'CICD ongoing... :eyes:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{env.JAVA_DISTRO}}
          cache: 'maven'
          check-latest: false

      - name: Build Number
        id: build-number
        run: echo "::set-output name=BUILD_NUMBER::$(date '+%-d.%-m.%Y.%-H.%-M.%-S')"

      - name: Docker Login
        uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Maven Clean Package and Push to Dockerhub
        run: |
          ./mvnw --no-transfer-progress clean package \
            -P build-frontend \
            -P jib-push-to-dockerhub \
              -Dapp.image.tag=${{steps.build-number.outputs.BUILD_NUMBER}}
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ':white_check_mark: pushed DmitriKonnovNN/ExamMicroService:${{steps.build-number.outputs.BUILD_NUMBER}} to docker hub... https://hub.docker.com/repository/docker/dmitriikonnovnn/exam-microservice-fs'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Update and commit app version in docker-compose.yaml
        run: |
          BUILD_NUMBER=${{steps.build-number.outputs.BUILD_NUMBER}}
          echo -e "Current elasticbeanstalk/staging/docker-compose.yaml\n$(cat elasticbeanstalk/staging/docker-compose.yaml)"
          sed -i -E 's_(dmitriikonnovnn/exam-microservice-fs:)([^"]*)_\1'${BUILD_NUMBER}'_' elasticbeanstalk/staging/docker-compose.yaml
          echo -e "Current elasticbeanstalk/staging/docker-compose.yaml\n$(cat elasticbeanstalk/staging/docker-compose.yaml)"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add elasticbeanstalk/staging/docker-compose.yaml
          git commit -m "new app version: ${BUILD_NUMBER}"
          git push

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ':elasticbeanstalk: :aws: Staging started... :grimacing: :crossed_fingers:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@ebe3476a4ce991d54336935e75e78dd9d86f9408
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID_TF_EXAM }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_TF_EXAM }}
          region: ${{ env.AWS_REGION }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
          application_name: ${{ env.EB_APPLICATION_NAME }}
          deployment_package: ${{ env.EB_DEPLOYMENT_PACKAGE }}
          version_label: ${{ steps.build-number.outputs.BUILD_NUMBER }}
          version_description: Version ${{steps.build-number.outputs.BUILD_NUMBER}} deployed into staging via github actions ${{ github.sha }}
          wait_for_deployment: 60
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          text: ':tada: :arrow_right: exam-managing-dev.eu-central-1.elasticbeanstalk.com'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if:
          always()